version: '1'
services:
  - type: web
    name: yuchi-server
    runtime: node
    repo: https://github.com/yushaku/yuchi-server
    plan: free
    envVars:
      - key: BUN_VERSION
        value: 1.3.0
    region: oregon
    buildCommand: bun install
    startCommand: bun run db:generate && bun run build && chmod +x server && ./server
